version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=3a515377
      - POSTGRES_DB=db_easysell
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"
